[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyDdkfFy_y0wAyyxC_ixzniD1vOyWTTvctk"
